### ISSUE TITLE
Migrate to Xtext Builder Plugin

### ISSUE THREAD

**Issue by szarnyasg** [ghillairet/xcore-gradle-example#2]
I managed to migrate the example to the Xtext Builder Plugin, which supports is supported in Gradle 3.0+: https://github.com/szarnyasg/xcore-gradle-example/tree/gradle-3.1

**Comment by szarnyasg** [comment]
Btw this repository is mentioned at https://blogs.itemis.com/en/using-xtext-with-xcore-and-gradle

**Comment by ghillairet** [comment]
Could you make a pull request for that, we would move the current master in a branch 2.xx, and have Gradle 3.xx in master instead.

**Comment by szarnyasg** [comment]
Sure!
